config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications_settings
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :money_ops
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  get "operations_status" => "money_ops#operations_status" 
  get "wallets_status" => "user_wallets#wallets_status"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card"
      get "cards_status" => "cards#cards_status"
      resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :user_wallets
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :notifications_settings
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
    end
  end
  
end

app/models/wallets_transfer_ratio.rb
class WalletsTransferRatio < ApplicationRecord
end

app/controllers/wallets_transfer_ratios_controller.rb
class WalletsTransferRatiosController < ApplicationController
  before_action :set_wallets_transfer_ratio, only: [:edit, :update]

  def index
    @wallets_transfer_ratios = WalletsTransferRatio.all
  end

  def new
    @wallets_transfer_ratio = WalletsTransferRatio.new
  end

  def edit
  end

  def create
    @wallets_transfer_ratio = WalletsTransferRatio.new(wallets_transfer_ratio_params)

    respond_to do |format|
      if @wallets_transfer_ratio.save
        format.html { redirect_to @wallets_transfer_ratio, notice: 'Wallets transfer ratio was successfully created.' }
        format.json { render :show, status: :created, location: @wallets_transfer_ratio }
      else
        format.html { render :new }
        format.json { render json: @wallets_transfer_ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @wallets_transfer_ratio.update(wallets_transfer_ratio_params)
        format.html { redirect_to wallets_transfer_ratios_path, notice: 'Wallets transfer ratio was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallets_transfer_ratio }
      else
        format.html { render :edit }
        format.json { render json: @wallets_transfer_ratio.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallets_transfer_ratio
      @wallets_transfer_ratio = WalletsTransferRatio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallets_transfer_ratio_params
      params.require(:wallets_transfer_ratio).permit(:key, :value, :description)
    end
end

app/helpers/wallets_transfer_ratios_helper.rb
module WalletsTransferRatiosHelper
end

app/views/wallets_transfer_ratios/_form.html.erb
<%= form_with(model: wallets_transfer_ratio, local: true) do |form| %>
  <% if wallets_transfer_ratio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallets_transfer_ratio.errors.count, "error") %> prohibited this wallets_transfer_ratio from being saved:</h2>

      <ul>
      <% wallets_transfer_ratio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :key %>
    <%= form.text_field :key %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallets_transfer_ratios/edit.html.erb
<%= form_with(model: @wallets_transfer_ratio, local: true) do |form| %>
    <% if @wallets_transfer_ratio.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@wallets_transfer_ratio.errors.count, "error") %> prohibited this wallets_transfer_ratio from being saved:</h2>
  
        <ul>
        <% @wallets_transfer_ratio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <h3> Key: <%= @wallets_transfer_ratio.key %></h3>
  
    <div class="field">
      <%= form.label :value %>
      <%= form.text_field :value %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Back', wallets_transfer_ratios_path %>

app/views/wallets_transfer_ratios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallets Transfer Ratios</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallets_transfer_ratios.each do |wallets_transfer_ratio| %>
      <tr>
        <td><%= wallets_transfer_ratio.key %></td>
        <td><%= wallets_transfer_ratio.value %></td>
        <td><%= wallets_transfer_ratio.description %></td>
        <td><%= link_to 'Edit', edit_wallets_transfer_ratio_path(wallets_transfer_ratio) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallets Transfer Ratio', new_wallets_transfer_ratio_path %>

app/views/wallets_transfer_ratios/new.html.erb
<h1>New Wallets Transfer Ratio</h1>

<%= render 'form', wallets_transfer_ratio: @wallets_transfer_ratio %>

<%= link_to 'Back', wallets_transfer_ratios_path %>