config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications_settings
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :money_ops
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  get "operations_status" => "money_ops#operations_status" 
  get "wallets_status" => "user_wallets#wallets_status"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card"
      get "cards_status" => "cards#cards_status"
      resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :user_wallets
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      resources :notifications_settings
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
    end
  end
  
end

app/models/notifications_setting.rb
class NotificationsSetting < ApplicationRecord
    validates_uniqueness_of :user_id
    
    # check which of these notifications will be enabled (mail only , message only , both mail and message)
    # @param [Integer] money_transactions_mail enable mail notifications for money transactions(1 for mail).
    # @param [Integer] money_transactions_message enable message notifications for money transactions(2 for message).
    # @param [Integer] pending_transactions_mail enable mail notifications for pending transactions(1 for mail).
    # @param [Integer] pending_transactions_message enable message notifications for pending transactions(2 for message).
    # @param [Integer] transactions_updates_mail enable mail notifications for current transactions updates(1 for mail).
    # @param [Integer] transactions_updates_message enable message notifications for current transactions updates(2 for message).
    # @param [Integer] help_tickets_updates enable mail notifications for help tickets updates(1 for mail).
    # @param [Integer] help_tickets_updates enable message notifications for help tickets updates(2 for message).
    # @param [Integer] tickets_replies enable mail notifications for new ticket replies(1 for mail).
    # @param [Integer] tickets_replies enable message notifications for new ticket replies(2 for message).
    # @param [Integer] account_login enable mail notifications for login to user account(1 for mail).
    # @param [Integer] account_login enable message notifications for login to user account(2 for message).
    # @param [Integer] change_password enable mail notifications for change password(1 for mail).
    # @param [Integer] change_password enable message notifications for change password(2 for message).
    # @param [Integer] verifications_setting enable mail notifications for two factor auth status(1 for mail).
    # @param [Integer] verifications_setting enable message notifications for two factor auth status(2 for message).
    # @return [money_transactions] Withdrawal,transfer and remittance transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [pending_transactions] pending transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [transactions_updates] current transactions updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [help_tickets_updates] help tickets updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [tickets_replies] new ticket replies(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [account_login] login to user account(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [change_password] change password(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    # @return [verifications_setting] when enable or disable two factor auth(0 for non ,1 for mail ,2 for message ,3 for mail & message).
    def self.usernotification(money_transactions_mail,money_transactions_sms,pending_transactions_mail,pending_transactions_sms,
      transactions_updates_mail,transactions_updates_sms,help_tickets_updates_mail,help_tickets_updates_sms,tickets_replies_mail,
      tickets_replies_sms,account_login_mail,account_login_sms,change_password_mail,change_password_sms,verifications_setting_mail,
      verifications_setting_sms)
  
      if money_transactions_mail == 1 && money_transactions_sms == 1
        @money_transactions = 3
      elsif money_transactions_sms == 1
        @money_transactions = 2
      elsif money_transactions_mail == 1
        @money_transactions = 1 
      else
        @money_transactions = 0
      end

      if pending_transactions_mail == 1 && pending_transactions_sms == 1
      @pending_transactions = 3
      elsif pending_transactions_sms == 1
      @pending_transactions = 2
      elsif pending_transactions_mail == 1
      @pending_transactions = 1 
      else
      @pending_transactions = 0
      end

      if transactions_updates_mail == 1 && transactions_updates_sms == 1
      @transactions_updates = 3
      elsif transactions_updates_sms == 1
      @transactions_updates = 2
      elsif transactions_updates_mail == 1
      @transactions_updates = 1 
      else
      @transactions_updates = 0
      end

      if help_tickets_updates_mail == 1 && help_tickets_updates_sms == 1
      @help_tickets_updates = 3
      elsif help_tickets_updates_sms == 1
      @help_tickets_updates = 2
      elsif help_tickets_updates_mail == 1
      @help_tickets_updates = 1 
      else
      @help_tickets_updates = 0
      end


      if tickets_replies_mail == 1 && tickets_replies_sms == 1
      @tickets_replies = 3
      elsif tickets_replies_sms == 1
      @tickets_replies = 2
      elsif tickets_replies_mail == 1
      @tickets_replies = 1 
      else
      @tickets_replies = 0
      end

      if account_login_mail == 1 && account_login_sms == 1
      @account_login = 3
      elsif account_login_sms == 1
      @account_login = 2
      elsif account_login_mail == 1
      @account_login = 1 
      else
      @account_login = 0
      end

      if change_password_mail == 1 && change_password_sms == 1
      @change_password = 3
      elsif change_password_sms == 1
      @change_password = 2
      elsif change_password_mail == 1
      @change_password = 1
      else
      @change_password = 0 
      end

      if verifications_setting_mail == 1 && verifications_setting_sms == 1
      @verifications_setting = 3
      elsif verifications_setting_sms == 1
      @verifications_setting = 2
      elsif verifications_setting_mail == 1
      @verifications_setting = 1 
      else
      @verifications_setting = 0
      end

      return @money_transactions,@pending_transactions,@transactions_updates,@help_tickets_updates,@tickets_replies,
      @account_login,@change_password,@verifications_setting
  
    end
  
  end
  

app/controllers/api/v1/notifications_settings_controller.rb
module Api
  module V1
    class NotificationsSettingsController < ApplicationController
      before_action :set_notifications_setting, only: [:edit, :update]
      skip_before_action :verify_authenticity_token

      # GET /notifications_settings
      def index

        @notifications_settings = NotificationsSetting.all
        respond_to do |format|
          format.json { render json: @notifications_settings }
        end

        # =begin
        # @api {get} /api/v1/notifications_settings 1-Request notifications settings List
        # @apiVersion 0.3.0
        # @apiName GetNotificationsSettings
        # @apiGroup Notifications Settings
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/notifications_settings
        # @apiSuccess {Number} id notification setting unique ID.
        # @apiSuccess {Number} user_id notification setting user ID.
        # @apiSuccess {Number} money_transactions Withdrawal,transfer and remittance transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} pending_transactions pending transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} transactions_updates current transactions updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} help_tickets_updates help tickets updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} tickets_replies new ticket replies(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} account_login login to user account(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} change_password change password(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} verifications_setting when enable or disable two factor auth(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # [
        #   {
        #       "id": 1,
        #       "user_id": 1,
        #       "money_transactions": 3,
        #       "pending_transactions": 1,
        #       "transactions_updates": 1,
        #       "help_tickets_updates": 3,
        #       "tickets_replies": 1,
        #       "account_login": 0,
        #       "change_password": 1,
        #       "verifications_setting": 3,
        #       "created_at": "2018-08-09T11:20:01.741Z",
        #       "updated_at": "2018-08-09T11:20:01.741Z"
        #   },
        #   {
        #       "id": 2,
        #       "user_id": 2,
        #       "money_transactions": 1,
        #       "pending_transactions": 2,
        #       "transactions_updates": 1,
        #       "help_tickets_updates": 1,
        #       "tickets_replies": 3,
        #       "account_login": 0,
        #       "change_password": 0,
        #       "verifications_setting": 2,
        #       "created_at": "2018-08-09T11:21:11.770Z",
        #       "updated_at": "2018-08-09T11:22:21.779Z"
        #   }
        # ]
        # @apiError MissingToken invalid Token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

      end


      # GET /notifications_settings/new
      def new
        @notifications_setting = NotificationsSetting.new
      end

      # GET /notifications_settings/id/edit
      def edit
      end

      # POST /notifications_settings
      def create

        # =begin
        # @api {post} /api/v1/notifications_settings 2-Create a Notification Settings
        # @apiVersion 0.3.0
        # @apiName PostNotificationsSettings
        # @apiGroup Notifications Settings
        # @apiExample Example usage:
        # curl -X POST \
        # http://localhost:3000/api/v1/notifications_settings \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        # "user_id": 4,
        # "money_transactions": 1,
        # "pending_transactions": 1,
        # "transactions_updates": 3,
        # "help_tickets_updates": 0,
        # "tickets_replies": 2,
        # "account_login": 0,
        # "change_password": 1,
        # "verifications_setting": 2
        # }'
        # @apiParam {Number} user_id notification setting user ID.
        # @apiParam {Number} money_transactions Withdrawal,transfer and remittance transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} pending_transactions pending transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} transactions_updates current transactions updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} help_tickets_updates help tickets updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} tickets_replies new ticket replies(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} account_login login to user account(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} change_password change password(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} verifications_setting when enable or disable two factor auth(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} id notification setting unique ID.
        # @apiSuccess {Number} user_id notification setting user ID.
        # @apiSuccess {Number} money_transactions Withdrawal,transfer and remittance transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} pending_transactions pending transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} transactions_updates current transactions updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} help_tickets_updates help tickets updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} tickets_replies new ticket replies(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} account_login login to user account(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} change_password change password(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Number} verifications_setting when enable or disable two factor auth(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # {
        #   "id": 4,
        #   "user_id": 4,
        #   "money_transactions": 1,
        #   "pending_transactions": 1,
        #   "transactions_updates": 3,
        #   "help_tickets_updates": 0,
        #   "tickets_replies": 2,
        #   "account_login": 0,
        #   "change_password": 1,
        #   "verifications_setting": 2,
        #   "created_at": "2018-08-11T07:51:33.838Z",
        #   "updated_at": "2018-08-11T07:51:33.838Z"
        # }
        # @apiError MissingToken missing user name or password.
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 422 Missing token
        #   {
        #     "error": "Missing token"
        #   }
        # @apiError ExistingUser User id has already been taken.
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 Existing User ID
        #   {
        #     "error": "has already been taken"
        #   }
        # =end

        @notifications_setting = NotificationsSetting.new(notifications_setting_params)

        respond_to do |format|
          if @notifications_setting.save
            format.json { render json: @notifications_setting, status: :created, location: @notifications_setting }
          else
            format.json { render json: @notifications_setting.errors, status: :unprocessable_entity }
          end
        end
        
      end

      # PATCH/PUT /notifications_settings/id
      def update

        # =begin
        # @api {put} /api/v1/notifications_settings/{:id} 3-Update an existing Notification Settings
        # @apiVersion 0.3.0
        # @apiName PutNotificationSettings
        # @apiGroup Notifications Settings
        # @apiExample Example usage:
        # curl -X PUT \
        # http://localhost:3000/api/v1/notifications_settings/3 \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        # "money_transactions": 2,
        # "pending_transactions": 1,
        # "transactions_updates": 3,
        # "help_tickets_updates": 3,
        # "tickets_replies": 2,
        # "account_login": 1,
        # "change_password": 0,
        # "verifications_setting": 3
        # }'
        # @apiParam {Number} money_transactions Withdrawal,transfer and remittance transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} pending_transactions pending transactions(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} transactions_updates current transactions updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} help_tickets_updates help tickets updates(0 for non ,1 for mail ,2 for message ,3 for mail & message).
        # @apiParam {Number} tickets_replies new ticket replies(0 for non ,1 for mail ,2 for message ,3 for mail & message).

app/helpers/notifications_settings_helper.rb
module NotificationsSettingsHelper
end

app/views/notifications_settings/edit.html.erb
<h1>User Notifications Setting</h1>

<%= form_with(model: @notifications_setting, local: true) do |form| %>
    <% if @notifications_setting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@notifications_setting.errors.count, "error") %> prohibited this notifications_setting from being saved:</h2>
  
        <ul>
        <% @notifications_setting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <p>
    <strong>المستخدم:</strong>
      <%= @notifications_setting.user_id %>
    </p>
    
    <h3>تنبيهات المعاملات </h3>
  
    <div class="field">
    <%= "معاملات الارسال ولالاستقبال والسحب" %>
      <% if @notifications_setting.money_transactions == 3 %>
      <%= form.check_box :money_transactions_mail ,checked: true%>Email <%= form.check_box :money_transactions_sms ,checked: true %>SMS
      <% elsif @notifications_setting.money_transactions == 2 %>
      <%= form.check_box :money_transactions_mail %>Email <%= form.check_box :money_transactions_sms ,checked: true %>SMS
      <% elsif @notifications_setting.money_transactions == 1 %>
      <%= form.check_box :money_transactions_mail  ,checked: true%>Email <%= form.check_box :money_transactions_sms %>SMS
      <% elsif @notifications_setting.money_transactions == 0 %>
      <%= form.check_box :money_transactions_mail %>Email <%= form.check_box :money_transactions_sms %>SMS
      <% end %>
    </div>
  
    <div class="field">
    <%= "المعاملات المعلقة" %>
        <% if @notifications_setting.pending_transactions == 3 %>
        <%= form.check_box :pending_transactions_mail ,checked: true%>Email <%= form.check_box :pending_transactions_sms ,checked: true %>SMS
        <% elsif @notifications_setting.pending_transactions == 2 %>
        <%= form.check_box :pending_transactions_mail %>Email <%= form.check_box :pending_transactions_sms ,checked: true %>SMS
        <% elsif @notifications_setting.pending_transactions == 1 %>
        <%= form.check_box :pending_transactions_mail  ,checked: true%>Email <%= form.check_box :pending_transactions_sms %>SMS
        <% elsif @notifications_setting.pending_transactions == 0 %>
        <%= form.check_box :pending_transactions_mail %>Email <%= form.check_box :pending_transactions_sms %>SMS
        <% end %>
    </div>
  
    <div class="field">
    <%= "تحديثات المعاملات الجارية" %>
    <% if @notifications_setting.transactions_updates == 3 %>
    <%= form.check_box :transactions_updates_mail ,checked: true%>Email <%= form.check_box :transactions_updates_sms ,checked: true %>SMS
    <% elsif @notifications_setting.transactions_updates == 2 %>
    <%= form.check_box :transactions_updates_mail %>Email <%= form.check_box :transactions_updates_sms ,checked: true %>SMS
    <% elsif @notifications_setting.transactions_updates == 1 %>
    <%= form.check_box :transactions_updates_mail  ,checked: true%>Email <%= form.check_box :transactions_updates_sms %>SMS
    <% elsif @notifications_setting.transactions_updates == 0 %>
    <%= form.check_box :transactions_updates_mail %>Email <%= form.check_box :transactions_updates_sms %>SMS
    <% end %>
    </div>
          
    <h3> تنبيهات الدعم الفنى</h3>
    <div class="field">
      <%= "تحديثات تذاكر الدعم" %>
      <% if @notifications_setting.help_tickets_updates == 3 %>
      <%= form.check_box :help_tickets_updates_mail ,checked: true%>Email <%= form.check_box :help_tickets_updates_sms ,checked: true %>SMS
      <% elsif @notifications_setting.help_tickets_updates == 2 %>
      <%= form.check_box :help_tickets_updates_mail %>Email <%= form.check_box :help_tickets_updates_sms ,checked: true %>SMS
      <% elsif @notifications_setting.help_tickets_updates == 1 %>
      <%= form.check_box :help_tickets_updates_mail  ,checked: true%>Email <%= form.check_box :help_tickets_updates_sms %>SMS
      <% elsif @notifications_setting.help_tickets_updates == 0 %>
      <%= form.check_box :help_tickets_updates_mail %>Email <%= form.check_box :help_tickets_updates_sms %>SMS
      <% end %>
    </div>
  
    <div class="field">
      <%= "الردود الجديدة على تذاكر الدعم" %>
      <% if @notifications_setting.tickets_replies == 3 %>
      <%= form.check_box :tickets_replies_mail ,checked: true%>Email <%= form.check_box :tickets_replies_sms ,checked: true %>SMS
      <% elsif @notifications_setting.tickets_replies == 2 %>
      <%= form.check_box :tickets_replies_mail %>Email <%= form.check_box :tickets_replies_sms ,checked: true %>SMS
      <% elsif @notifications_setting.tickets_replies == 1 %>
      <%= form.check_box :tickets_replies_mail  ,checked: true%>Email <%= form.check_box :tickets_replies_sms %>SMS
      <% elsif @notifications_setting.tickets_replies == 0 %>
      <%= form.check_box :tickets_replies_mail %>Email <%= form.check_box :tickets_replies_sms %>SMS
      <% end %>
    </div>
  
    <h3>تنبيهات حماية حسابك</h3>
    <div class="field">
      <%= "تسجيل الدخول على حسابك" %>
      <% if @notifications_setting.account_login == 3 %>
      <%= form.check_box :account_login_mail ,checked: true%>Email <%= form.check_box :account_login_sms ,checked: true %>SMS
      <% elsif @notifications_setting.account_login == 2 %>
      <%= form.check_box :account_login_mail %>Email <%= form.check_box :account_login_sms ,checked: true %>SMS
      <% elsif @notifications_setting.account_login == 1 %>
      <%= form.check_box :account_login_mail  ,checked: true%>Email <%= form.check_box :account_login_sms %>SMS
      <% elsif @notifications_setting.account_login == 0 %>
      <%= form.check_box :account_login_mail %>Email <%= form.check_box :account_login_sms %>SMS
      <% end %>
    </div>
  
    <div class="field">
      <%= "عند تفعيل & إلغاء تفعيل اعدادات التحقق من خطوتين" %>
      <% if @notifications_setting.change_password == 3 %>
      <%= form.check_box :change_password_mail ,checked: true%>Email <%= form.check_box :change_password_sms ,checked: true %>SMS
      <% elsif @notifications_setting.change_password == 2 %>
      <%= form.check_box :change_password_mail %>Email <%= form.check_box :change_password_sms ,checked: true %>SMS
      <% elsif @notifications_setting.change_password == 1 %>
      <%= form.check_box :change_password_mail  ,checked: true%>Email <%= form.check_box :change_password_sms %>SMS
      <% elsif @notifications_setting.change_password == 0 %>
      <%= form.check_box :change_password_mail %>Email <%= form.check_box :change_password_sms %>SMS
      <% end %>
    </div>
  
    <div class="field">
      <%= "تغيير كلمة المرور" %>
      <% if @notifications_setting.verifications_setting == 3 %>
      <%= form.check_box :verifications_setting_mail ,checked: true%>Email <%= form.check_box :verifications_setting_sms ,checked: true %>SMS
      <% elsif @notifications_setting.verifications_setting == 2 %>
      <%= form.check_box :verifications_setting_mail %>Email <%= form.check_box :verifications_setting_sms ,checked: true %>SMS
      <% elsif @notifications_setting.verifications_setting == 1 %>
      <%= form.check_box :verifications_setting_mail  ,checked: true%>Email <%= form.check_box :verifications_setting_sms %>SMS
      <% elsif @notifications_setting.verifications_setting == 0 %>
      <%= form.check_box :verifications_setting_mail %>Email <%= form.check_box :verifications_setting_sms %>SMS
      <% end %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Back', notifications_settings_path %><br><br>

<% if @notifications_setting.user_id != 0 %>
<a title="Reture Defualt Notification Setting" onclick="return confirm_click();" href="/add_defualt_notifications?id=<%= @notifications_setting.id %>"><i class="icon-remove-sign">Reture Defualt Notification Setting</i></a>
<% end %>

<script type="text/javascript">
function confirm_click()
{
return confirm("Are you sure ?");
}
</script>

app/views/notifications_settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications Settings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Money transactions</th>
      <th>Pending transactions</th>
      <th>Transactions updates</th>
      <th>Help tickets updates</th>
      <th>Tickets replies</th>
      <th>Account login</th>
      <th>Change password</th>
      <th>Verifications setting</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications_settings.each do |notifications_setting| %>
      <tr>
        <% if notifications_setting.user_id == 0 %>
        <td><%= "Defualt" %></td>
        <% else %>
        <td><%= notifications_setting.user_id %></td>
        <% end %>
        <% if notifications_setting.money_transactions == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.money_transactions == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.money_transactions == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.money_transactions == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.pending_transactions == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.pending_transactions == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.pending_transactions == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.pending_transactions == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.transactions_updates == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.transactions_updates == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.transactions_updates == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.transactions_updates == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.help_tickets_updates == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.help_tickets_updates == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.help_tickets_updates == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.help_tickets_updates == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.tickets_replies == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.tickets_replies == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.tickets_replies == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.tickets_replies == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.account_login == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.account_login == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.account_login == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.account_login == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.change_password == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.change_password == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.change_password == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.change_password == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <% if notifications_setting.verifications_setting == 3 %>
        <td><%= "Email & Message" %></td>
        <% elsif notifications_setting.verifications_setting == 2 %>
        <td><%= "Message" %></td>
        <% elsif notifications_setting.verifications_setting == 1 %>
        <td><%= "Email" %></td>
        <% elsif notifications_setting.verifications_setting == 0 %>
        <td><%= "Non" %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_notifications_setting_path(notifications_setting) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notifications Setting', new_notifications_setting_path %>

app/views/notifications_settings/new.html.erb
<h1>Notifications Setting</h1>

<%= render 'form', notifications_setting: @notifications_setting %>

<%= link_to 'Back', notifications_settings_path %>

app/views/notifications_settings/update.html.erb
<%= debug(@result)%>